#!/usr/bin/env bash

set -euo pipefail

USAGE="usage: $0 <screen name>"

if ! command -v twurl &>/dev/null; then
  echo "run: $ gem install twurl" >&2
  exit 1
elif ! command -v jq &>/dev/null; then
  echo "install: jq" >&2
  exit 1
elif ! [ -f ~/.twurlrc ]; then
  echo "run: $ twurl authorize -c <consumer key> -s <consumer seckey>" >&2
  exit 1
elif [ $# -ne 1 ]; then
  echo "error: invalid arity $#, expected 1">&2
  echo "$USAGE" >&2
  exit 1
elif ! [[ "$1" =~ ^[a-zA-Z0-9_]+$ ]]; then
  echo "error: invalid name $1" >&2
  echo "$USAGE" >&2
  exit 1
fi

:>"${1}.followers.jsonl"
:>"${1}.followings.jsonl"

echo '[followers]'
cursor="-1"
# cursor="1691378750998315714"
cnt=0
while { [ "$cursor" != "0" ] && [ -n "$cursor" ];}; do
  echo -n $'\r\e[K'"[$((cnt*200+1)),$(((cnt+1)*200))]"
  res="$(
    twurl "/1.1/followers/list.json?screen_name=${1}&count=200&cursor=${cursor}"
  )"
  if echo "$res" | grep -q '^{"errors":'; then
    echo "error: response is invalid">&2
    echo "$res"
    exit 1
  fi
  cursor="$(
    echo "$res" | jq '.next_cursor'
  )"
  echo "$res" >> "${1}.followers.jsonl"
  echo -n '=>zzz...'
  sleep "$((RANDOM%5+60))s"
  ((cnt++))
done

echo
echo '[followings]'
cursor="-1"
cnt=0
while { [ "$cursor" != "0" ] && [ -n "$cursor" ];}; do
  echo -n $'\r\e[K'"[$((cnt*200+1)),$(((cnt+1)*200))]"
  res="$(
    twurl "/1.1/friends/list.json?screen_name=${1}&count=200&cursor=${cursor}"
  )"
  if echo "$res" | grep -q '^{"errors":'; then
    echo "error: response is invalid">&2
    echo "$res"
    exit 1
  fi
  cursor="$(
    echo "$res" | jq '.next_cursor'
  )"
  echo "$res" >> "${1}.followings.jsonl"
  echo -n '=>zzz...'
  sleep "$((RANDOM%5+60))s"
  ((cnt++))
done

echo
echo '[pp...]'
jq --slurp '.' "${1}.followers.jsonl" > "${1}.followers.jsonl.tmp"
mv "${1}.followers.jsonl.tmp" "${1}.followers.jsonl"
jq --slurp '.' "${1}.followings.jsonl" > "${1}.followings.jsonl.tmp"
mv "${1}.followings.jsonl.tmp" "${1}.followings.jsonl"

echo 'done!'
